# Generated by Django 4.0.2 on 2023-09-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_stor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stor',
        ),
    ]
