# Generated by Django 4.0.2 on 2023-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_customerexpence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
